const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
test('real webview has all referenced controls, strict CSP and no demo runtime',()=>{
 const html=fs.readFileSync('webview/main.html','utf8'),js=fs.readFileSync('webview/main.js','utf8');
 new vm.Script(js);
 const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);
 assert.equal(new Set(ids).size,ids.length);
 for(const [,id] of js.matchAll(/\$\('([^']+)'\)/g))assert.ok(ids.includes(id),id);
 for(const id of ['popout','export','import','settings','diagnostics','plugin-settings','creator','creator-dialog','creator-close','project','auto-reply','auto-edits','auto-commands','auto-reply-work','image-dialog','image-full','question-dialog','question-body','question-deny','snippets-toggle','snippets-panel','snippet-dialog','instruction-dialog','instruction-text'])assert.ok(ids.includes(id));
 assert.match(html,/id="creator"[^>]*>От создателя</);
 assert.match(html,/class="brand-text"/);
 assert.doesNotMatch(js,/brand-text/);
 assert.match(html,/script-src 'nonce-\{\{nonce\}\}'/);
 assert.doesNotMatch(html,/preview\.js|демонстрационные|ИНТЕРАКТИВНЫЙ МАКЕТ/);
 assert.doesNotMatch(js,/innerHTML|localStorage|simulate/);
 assert.match(js,/clientRequestId: requestId/);
 assert.match(js,/function formatElapsed/);
 assert.match(js,/setInterval\(paintTimes, 1000\)/);
 assert.match(js,/execCommand\('insertText'/);
 assert.doesNotMatch(js,/setRangeText\(/);
 assert.match(html,/id="instruction-text"[^>]*maxlength="1000"/);
 assert.doesNotMatch(js,/reload-spacer/);
});
test('dark palette takes text colour from the editor and the waiting buttons keep blinking',()=>{
 const css=fs.readFileSync('webview/main.css','utf8');
 const html=fs.readFileSync('webview/main.html','utf8');
 assert.match(css,/\.agent-field \.agent-instruction\{[^}]*width:30px/);
 assert.match(css,/\.message-tools \.instruction-used\[open\]/);
 assert.match(css,/:root\{[^}]*--fg:var\(--vscode-editor-foreground,/);
 assert.match(css,/mark\.current-match\{[^}]*color:#000/);
 assert.match(css,/\.queue-actions button\.next:not\(:disabled\),#permission-once\{[^}]*animation:awaiting-turn/);
 assert.match(html,/id="permission-dialog"/);
 assert.match(css,/steps\(1,end\)/);
 assert.match(css,/@keyframes awaiting-turn\{0%,49%\{background:var\(--focus\)/);
 // Anton's Windows turns client-area animation off, which the webview reads as
 // prefers-reduced-motion: reduce. A branch on it silently killed the blink for months.
 assert.doesNotMatch(css,/@media\(prefers-reduced-motion:reduce\)\{[^}]*(queue-actions button\.next|permission button\.primary)/);
 assert.doesNotMatch(css.slice(css.indexOf('.queue-actions button.next')),/^[^@]*animation:none/);
 assert.match(css,/#stop-all\{[^}]*border:1px solid var\(--line\)/);
 assert.match(css,/#stop-all\{[^}]*height:26px/);
 assert.match(css,/#stop-all\{[^}]*height:26px/);
 assert.match(html,/Стоп всем/);
 // Four buttons of different length used to wrap into ragged rows. One column keeps them even.
 assert.match(css,/#permission-dialog \.dialog-actions\{[^}]*grid-template-columns:minmax\(0,1fr\)/);
 assert.match(css,/#permission-dialog #permission-deny\{[^}]*justify-self:end/);
 assert.match(css,/\.trace-item:not\(:last-child\)::before\{[^}]*width:1px/);
 assert.match(css,/\.trace-dot\{[^}]*border-radius:50%/);
 assert.match(css,/\.md-table\{[^}]*border-collapse:collapse/);
 assert.match(css,/\.md-table th\{[^}]*white-space:nowrap/);
 assert.doesNotMatch(css,/\.md-table th,\.md-table td\{[^}]*overflow-wrap:anywhere/);
 assert.match(html,/>Работа:</);
 assert.match(html,/Очередь ответов/);
 assert.doesNotMatch(html,/<h2>Сейчас<\/h2>/);
 assert.doesNotMatch(html,/Ответы на текущий вопрос/);
 assert.match(css,/\.work-head\{[^}]*display:flex/);
 assert.match(css,/\.queue-slot\{[^}]*min-height:40px/);
 assert.match(css,/\.queue-actions\{[^}]*flex-wrap:wrap/);
 assert.match(css,/\.queue-actions button\{[^}]*white-space:pre-line/);
 assert.match(css,/\.queue-actions button\{[^}]*flex:1 1 4\.5em/);
 assert.match(css,/\.notice\{position:sticky/);
 assert.match(css,/\.message\.event\{/);
 assert.doesNotMatch(html,/permissions-block/);
 assert.ok(html.indexOf('id="agents"')>0);
 assert.match(css,/\.meter\{/);assert.match(css,/\.meter-text\{[^}]*justify-content:center/);
 assert.match(css,/\.agent \.usage-one\{/);
 assert.match(css,/\.meter\.high \.meter-fill\{[^}]*--warn/);
 assert.match(css,/\.meter\.over \.meter-fill\{[^}]*--danger/);
 assert.match(css,/\.usage-fill\{/);
 assert.match(css,/\.usage-one\.high \.usage-fill\{[^}]*--warn/);
 assert.match(css,/\.usage-one\.over \.usage-fill\{[^}]*--danger/);
 assert.match(css,/#permission-more>summary\{[^}]*cursor:pointer/);
 assert.match(css,/\.agent-actions button,\.agent-side button,\.agent \.usage-one\{[^}]*width:42px/);
 assert.match(css,/\.agent-actions button,\.agent-side button,\.agent \.usage-one\{[^}]*height:26px/);
 assert.match(css,/\.agent-actions,\.agent-side\{[^}]*width:94px/);
 assert.match(css,/\.agent-field\{[^}]*flex-wrap:wrap/);
 assert.match(css,/\.agent-field \.agent-mode\{[^}]*min-width:min\(100%,/);
 assert.match(html,/id="usage-dialog"/);
 assert.match(html,/id="project"/);
 assert.match(html,/id="plugin-settings"/);
 assert.match(css,/\.project-slot\{[^}]*flex:1/);
 assert.match(css,/\.project-path\{[^}]*flex:0 1 auto/);
 assert.match(css,/\.toolbar button\.project-path\{[^}]*font-size:16px/);
 assert.match(css,/\.image-thumb-img\{[^}]*max-height:160px/);
 assert.match(html,/img-src \{\{cspSource\}\} data: https:/);
 assert.match(css,/#permission-more>summary\{[^}]*border:0/);
 assert.match(css,/minmax\(380px,min\(var\(--controls-width\)/);
 assert.match(html,/aria-valuemin="380"/);
 assert.match(html,/Заготовки/);
 assert.match(html,/id="snippets-toggle"/);
 assert.match(html,/id="snippets-from-field"/);
 assert.match(html,/class="composer-hint"/);
 assert.match(html,/Shift\+Enter — новая строка/);
 assert.match(html,/class="snippets-hint"/);
 assert.match(html,/Ctrl\+Z в поле — отменить вставку/);
 assert.match(css,/\.composer-hint,\.snippets-hint\{[^}]*font-size:11px/);
 assert.match(html,/class="snippets-toolbar"/);
 assert.match(html,/>\+<\/button>/);
 assert.match(html,/Пока пусто/);
 assert.doesNotMatch(html,/snippets-list[\s\S]*snippets-from-field/);
 assert.match(css,/\.snippets-toolbar\{[^}]*display:flex/);
 assert.match(css,/#snippets-from-field\{[^}]*width:26px/);
 assert.doesNotMatch(css,/#snippets-from-field\{[^}]*width:100%/);
 assert.match(css,/#snippets-panel\{[^}]*position:fixed/);
 assert.match(css,/#snippets-panel\{[^}]*max-height:50vh/);
 assert.match(css,/\.snippet-row \.snippet-name\{[^}]*text-overflow:ellipsis/);
 assert.match(css,/\.snippet-row\{[^}]*display:flex/);
 assert.match(html,/h2 class="plain"/);
 assert.doesNotMatch(html,/block-hint/);
 assert.match(html,/id="search-toggle"[^>]*title="/);
 assert.match(html,/id="export"[^>]*title="/);
 assert.match(html,/id="import"[^>]*title="/);
 // Above .3 the percentage inside the warning fill drops below 4.5:1 on the dark palette.
 const fill=css.match(/\.meter-fill\{[^}]*opacity:([\d.]+)/);
 assert.ok(fill&&Number(fill[1])<=0.3,'meter fill opacity keeps the label readable: '+fill?.[1]);
});
test('context meter shows a dash instead of zero, and never hides a figure above the window',()=>{
 const js=fs.readFileSync('webview/main.js','utf8');
 const body=js.slice(js.indexOf('function meter'),js.indexOf('function field'));
 assert.match(body,/typeof usage\.tokens === 'number'/);
 assert.ok(body.includes("'—'"));
 assert.match(body,/role', 'progressbar/);
 assert.ok(body.includes('Это не лимит ленты Trio.'));
 // Only the fill is clamped. A clamped percentage would have passed 336% off as a tidy 100%.
 assert.match(body,/percent > 100/);
 assert.match(body,/fill\.style\.width = Math\.min\(100, percent/);
 assert.doesNotMatch(body,/percent = [^;]*Math\.min\(100/);
 assert.match(body,/percent >= 85/);
 assert.match(body,/compactTokens/);
 assert.match(body,/ из /);
 assert.match(body,/usage\.source/);
 assert.match(body,/Источник: /);
});
test('each post shows its date and time in Anton\'s own zone, service lines included',()=>{
 const js=fs.readFileSync('webview/main.js','utf8'),css=fs.readFileSync('webview/main.css','utf8');
 // A hard-coded zone would print Anton's evening as someone else's morning.
 assert.doesNotMatch(js,/timeZone/);
 assert.match(js,/new Intl\.DateTimeFormat\('ru-RU'/);
 assert.match(js,/\.message-stamp/);
 assert.match(js,/event-time/);
 assert.match(css,/\.message-stamp\{[^}]*white-space:pre-line/);
 assert.match(css,/\.message-stamp:empty\{display:none\}/);
 const src=js.slice(js.indexOf('const moment ='),js.indexOf('function paintStamp'));
 const {messageMoment}=new vm.Script(src+'\n({messageMoment})').runInNewContext({});
 const turn={startedAt:1000,endedAt:5000};
 assert.equal(messageMoment({author:'Антон',at:900},turn),900,'вопрос — по своему времени');
 assert.equal(messageMoment({author:'Колян',at:1000},turn),5000,'ответ — по концу хода');
 assert.equal(messageMoment({author:'Trio',control:true,at:4000},turn),4000,'служебная строка не берёт конец хода');
 // Feeds written before the stamp still order themselves by their turns.
 assert.equal(messageMoment({author:'Антон'},turn),1000);
 assert.equal(messageMoment({author:'Гриха'},turn),5000);
 assert.equal(messageMoment({author:'Колян',at:0},{startedAt:1000}),1000,'нулевое время не выдаётся за 1970-й');
 assert.equal(messageMoment({author:'Антон'},undefined),undefined);
});
